version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - php/install-packages
      - run:
          name: Copy .env
          command: cp .env.ci .env
      - run:
          name: Generate key
          command: php artisan key:generate
      - run:
          name: Run tests
          command: php artisan test
workflows:
  build-and-test:
    jobs:
      - test-php
